name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest # OS
    # strategy:
    #   matrix:
    #     go: ['1.21', '1.22']
    steps:
      - uses: actions/checkout@v4 # find user/repo action in github
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22 # ${{ matrix.go }}
      - run: go test
      - run: go run math.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: filipebarreto/ci-golang:latest