name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest # OS
    strategy:
      matrix:
        go: ['1.21', '1.22']
    steps:
      - uses: actions/checkout@v4 # find user/repo action in github
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run math.go