name: ci-golang-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest # OS
    steps:
      - uses: actions/checkout@v4 # find user/repo action in github
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - run: go test
      - run: go run math.go